/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
#include <stdio.h>
#include <android/log.h>

using namespace cv;
using namespace std;


#define  LOG_TAG    "your-log-tag"
#ifndef _Included_edu_hon5037tamu_detection_OpencvClass
#define _Included_edu_hon5037tamu_detection_OpencvClass
#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_hon5037tamu_detection_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */
 void detect(Mat& frame);

JNIEXPORT void JNICALL Java_edu_hon5037tamu_detection_OpencvClass_faceDetection
  (JNIEnv *, jclass,jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
